### PR TITLE
feat: rebase the url property inside css

### PR DESCRIPTION
**Pull request by csuZipple**
To solve the issue https://github.com/unlight/gulp-cssimport/issues/9
It is very important to automatically rebase the internal url of css when packaging, this plugin should need to support it.  :D

### CODE REVIEW

**Comment by unlight** [comment]
Can `transform` option https://github.com/unlight/gulp-cssimport#transform solve your rebase issue?

**Comment by csuZipple** [comment]
`transform` only changes css `@import`, cannot transform the property `background: url('')` in imported css... 
and this commit has unexpected performance in some special case...I will close it

**Comment by unlight** [comment]
I think changing `background: url()` is out of the scope of this plugin.
Please, check [these plugins](https://npms.io/search?q=gulp+css+rebase)

**Comment by unlight** [comment]
And I believe that it is not possible to do a correct rebase url for remote files.
```
@import('http://example.com/a.css')
```

**Comment by csuZipple** [comment]
in remote file like `@import('http://example.com/a.css') which include `background: url('someUrl')`, 
we can handle it with function below
```js
/**
 * 
 * @param absolutePath   import file path
 * @param relativePath     background's url
 * @returns {string|*}       return absolutePath start with http/https or C: or /Users 
 */
function computeAbsolutePathFromRelativePath(absolutePath, relativePath) {
    if(isUrl(relativePath) || relativePath.startsWith('/')){
        return relativePath
    }
    var dir = path.dirname(absolutePath) + '/';
    if(relativePath.startsWith('./')){
        return dir+relativePath.replace(/^\.\//, '')
    }
    while(relativePath.startsWith('../')){
        relativePath = relativePath.replace(/^\.\.\//, '');
        dir = path.dirname(dir) + '/'
    }
    return dir + relativePath
}
```

**Pull request closed without merging**
